import { useMemo, useState } from 'react'
import { Globe2, RotateCcw, Save, Settings } from 'lucide-react'
import InternalLayout from '../../components/internal/InternalLayout'
import InternalNotice from '../../components/internal/InternalNotice'
import { useSiteContent, type SiteIdentity } from '../../prototype/SiteContentContext'

export default function WebsiteSettingsPage() {
  const { identity, setIdentity } = useSiteContent()
  const [draft, setDraft] = useState<SiteIdentity>(() => ({ ...identity }))
  const [notice, setNotice] = useState('')
  const changed = useMemo(() => JSON.stringify(draft) !== JSON.stringify(identity), [draft, identity])
  const publish = () => { setIdentity({ ...draft }); setNotice('Identitas Draft dipublikasikan ke Navbar/Footer.'); window.setTimeout(() => setNotice(''), 3000) }
  return <InternalLayout title="Pengaturan Website" subtitle="Identitas publik, kontak resmi, dan konfigurasi website."><InternalNotice />{notice && <div role="status" className="mt-5 border border-[#E8D8B7] bg-[#FFF9EC] px-4 py-3 text-xs font-semibold text-[#6F5830]">{notice}</div>}<section className="mt-6 grid gap-6 xl:grid-cols-[1fr_0.9fr]">
    <div className="border border-border-soft bg-white p-5 sm:p-6"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-sage/60 text-forest"><Settings size={18}/></span><div><p className="eyebrow text-forest">IDENTITAS WEBSITE · DRAFT</p><h2 className="mt-2 text-xl font-extrabold text-charcoal">Informasi yang tampil ke publik.</h2></div></div><div className="mt-6 space-y-4"><label className="block"><span className="mb-2 block text-xs font-extrabold uppercase tracking-[0.1em] text-muted">Nama Website</span><input value={draft.name} onChange={(event) => setDraft({ ...draft, name:event.target.value })} className="h-12 w-full border border-border-soft bg-offwhite px-4 text-sm font-semibold outline-none focus:border-forest"/></label><label className="block"><span className="mb-2 block text-xs font-extrabold uppercase tracking-[0.1em] text-muted">Nama Pendek</span><input value={draft.shortName} onChange={(event) => setDraft({ ...draft, shortName:event.target.value })} className="h-12 w-full border border-border-soft bg-offwhite px-4 text-sm font-semibold outline-none focus:border-forest"/></label><label className="block"><span className="mb-2 block text-xs font-extrabold uppercase tracking-[0.1em] text-muted">Lokasi Umum</span><input value={draft.locationLabel} onChange={(event) => setDraft({ ...draft, locationLabel:event.target.value })} className="h-12 w-full border border-border-soft bg-offwhite px-4 text-sm font-semibold outline-none focus:border-forest"/></label><label className="block"><span className="mb-2 block text-xs font-extrabold uppercase tracking-[0.1em] text-muted">Email Resmi</span><input value={draft.email} onChange={(event) => setDraft({ ...draft, email:event.target.value })} placeholder="Belum diisi" className="h-12 w-full border border-border-soft bg-offwhite px-4 text-sm font-semibold outline-none focus:border-forest"/></label><div className="flex gap-2"><button type="button" disabled={!changed} className="btn btn-secondary disabled:opacity-40" onClick={() => setDraft({ ...identity })}><RotateCcw size={16}/> Reset</button><button type="button" disabled={!changed} className="btn btn-primary disabled:opacity-40" onClick={publish}><Save size={16}/> Publish</button></div></div></div>
    <div className="border border-border-soft bg-white p-5 sm:p-6"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-sage/60 text-forest"><Globe2 size={18}/></span><div><p className="eyebrow text-forest">KONFIGURASI PUBLIK</p><h2 className="mt-2 text-xl font-extrabold text-charcoal">Batas yang aman untuk Superadmin.</h2></div></div><div className="mt-6 divide-y divide-border-soft border-y border-border-soft">{[['Konten & Media','Kelola teks, foto, section, dan dokumen publik.'],['Design System','Kelola token tampilan yang diizinkan tanpa mengubah kode bebas.'],['Navigasi','Atur menu dan halaman yang terlihat masyarakat.'],['Akun Admin','Menentukan pengelola operasional organisasi.']].map(([title,note]) => <div key={title} className="py-4"><p className="text-sm font-extrabold text-charcoal">{title}</p><p className="mt-1 text-xs leading-relaxed text-muted">{note}</p></div>)}</div><p className="mt-5 text-xs leading-relaxed text-muted">Superadmin tidak memiliki menu transaksi, verifikasi kegiatan, penugasan Humas, RAB, atau LPJ. Semua fitur itu berada di Admin.</p></div>
  </section></InternalLayout>
}
