import { useMemo, useState } from 'react'
import { Eye, EyeOff, FileText, RotateCcw, Save, ShieldCheck } from 'lucide-react'
import InternalLayout from '../../components/internal/InternalLayout'
import InternalNotice from '../../components/internal/InternalNotice'
import { useSiteContent, type ManagedDocument } from '../../prototype/SiteContentContext'

export default function WebsiteDocumentsPage() {
  const { documents, setDocuments } = useSiteContent()
  const [draft, setDraft] = useState<ManagedDocument[]>(() => documents.map((item) => ({ ...item })))
  const [notice, setNotice] = useState('')
  const changed = useMemo(() => JSON.stringify(draft) !== JSON.stringify(documents), [draft, documents])
  const publish = () => { setDocuments(draft.map((item) => ({ ...item }))); setNotice('Status publikasi dokumen diterapkan ke /keabsahan.'); window.setTimeout(() => setNotice(''), 3000) }
  return <InternalLayout title="Dokumen Publik" subtitle="Kontrol dokumen keabsahan yang boleh ditampilkan pada website publik."><InternalNotice />{notice && <div role="status" className="mt-5 border border-[#E8D8B7] bg-[#FFF9EC] px-4 py-3 text-xs font-semibold text-[#6F5830]">{notice}</div>}<section className="mt-6 border border-border-soft bg-white"><div className="flex flex-col gap-4 border-b border-border-soft px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-sage/60 text-forest"><ShieldCheck size={18}/></span><div><p className="eyebrow text-forest">PUBLIKASI DOKUMEN · DRAFT</p><h2 className="mt-2 text-xl font-extrabold text-charcoal">Keabsahan tetap terkontrol.</h2><p className="mt-2 text-xs leading-relaxed text-muted">Perubahan baru tampil pada /keabsahan setelah Publish.</p></div></div><div className="flex gap-2"><button type="button" disabled={!changed} onClick={() => setDraft(documents.map((item) => ({ ...item })))} className="btn btn-secondary disabled:opacity-40"><RotateCcw size={15}/> Reset</button><button type="button" disabled={!changed} onClick={publish} className="btn btn-primary disabled:opacity-40"><Save size={15}/> Publish</button></div></div><div className="divide-y divide-border-soft">{draft.map((item) => <div key={item.id} className="grid gap-3 px-5 py-5 sm:grid-cols-[44px_1fr_auto] sm:items-center sm:px-6"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-warmwhite text-forest"><FileText size={18}/></span><div><p className="text-sm font-extrabold text-charcoal">{item.title}</p><p className="mt-1 text-xs text-muted">{item.status} · {item.period}</p></div><button type="button" onClick={() => setDraft(draft.map((doc) => doc.id===item.id ? { ...doc, publicVisible: !doc.publicVisible } : doc))} className={`inline-flex w-fit items-center gap-2 px-2.5 py-1 text-[0.65rem] font-extrabold uppercase tracking-[0.08em] ${item.publicVisible ? 'bg-sage/65 text-forest' : 'bg-warmwhite text-muted'}`}>{item.publicVisible ? <Eye size={13}/> : <EyeOff size={13}/>} {item.publicVisible ? 'Akan tampil' : 'Akan disembunyikan'}</button></div>)}</div></section></InternalLayout>
}
